cloud:
  aws:
    credentials:
      access-key: AKIASQOIXWCQ5XBVX2CS
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false
application:
  bucket:
    name: trip-partner-user-profile
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB